apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resultserver-deploy
  name: resultserver-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultserver-deploy
  template:
    metadata:
      labels:
        app: resultserver-deploy
    spec:
      containers:
      - image: zbyr/result_server
        name: resultserver
        ports:
          - containerPort: 80
        env:
          - name: MYSQL_DATABASE_HOST
            value: mysql-service
          - name: MYSQL_DATABASE
            value: "phonebook"
          - name: MYSQL_USER
            value: "zbyr"
          - name: MYSQL_PASSWORD
            value: "abc123"

