apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver-deploy
  name: webserver-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver-deploy
  template:
    metadata:
      labels:
        app: webserver-deploy
    spec:
      containers:
      - image: zbyr/webserver
        name: webserver
        ports:
          - containerPort: 80
        env:
          - name: MYSQL_DATABASE_HOST
            value: mysql-service
          - name: MYSQL_DATABASE
            value: "phonebook"
          - name: MYSQL_USER
            value: "zbyr"
          - name: MYSQL_PASSWORD
            value: "abc123"

